// AUTO-GENERATED by tools/embed_frontend.py from templates/frontend.html -- do not edit by hand.
#pragma once

inline const char kFrontendTemplate[] = R"MGHTML(<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini-Git &middot; Repository Studio</title>
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- FontAwesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Google Fonts Inter & JetBrains Mono -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet">
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        git: {
                            dark: '#000000',
                            card: '#0A0A0A',
                            border: '#222222',
                            text: '#FFFFFF',
                            muted: '#888888',
                        }
                    },
                    fontFamily: {
                        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', 'Inter', 'sans-serif'],
                        mono: ['"JetBrains Mono"', '"SF Mono"', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
                    }
                }
            }
        }
    </script>
    <style>
        /* Pure Black and White Canvas */
        body {
            background-color: #000000;
            color: #FFFFFF;
        }

        /* Pure Monochrome Surface Panels */
        .liquid-glass {
            background: #0A0A0A;
            border: 1px solid #222222;
            box-shadow: 0 16px 40px -10px rgba(0, 0, 0, 0.9), inset 0 1px 0 rgba(255, 255, 255, 0.08);
        }

        .liquid-glass-subtle {
            background: #111111;
            border: 1px solid #222222;
        }

        .liquid-pill {
            background: #141414;
            border: 1px solid #2A2A2A;
            color: #FFFFFF;
            transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
        }
        .liquid-pill:hover {
            background: #202020;
            border-color: #444444;
            transform: translateY(-0.5px);
        }
        .liquid-pill:active {
            transform: scale(0.97);
        }

        /* Segmented Control Pill Classes */
        .segmented-track {
            background: #0E0E0E;
            border: 1px solid #262626;
        }

        .segmented-pill-active {
            background: #2C67C5 !important;
            color: #FFFFFF !important;
        }

        .segmented-pill-inactive {
            color: #888888 !important;
        }
        .segmented-pill-inactive:hover {
            color: #FFFFFF !important;
            background: rgba(44, 103, 197, 0.15) !important;
        }

        /* Custom Scrollbars */
        ::-webkit-scrollbar {
            width: 5px;
            height: 5px;
        }
        ::-webkit-scrollbar-track {
            background: #000000;
        }
        ::-webkit-scrollbar-thumb {
            background: #2A2A2A;
            border-radius: 9999px;
        }
        ::-webkit-scrollbar-thumb:hover {
            background: #2C67C5;
        }

        /* Diff Highlighting */
        .diff-added {
            background-color: rgba(44, 103, 197, 0.16);
            color: #FFFFFF;
            border-left: 2px solid #2C67C5;
            font-weight: 500;
        }
        .diff-removed {
            background-color: rgba(255, 255, 255, 0.03);
            color: #666666;
            text-decoration: line-through;
            border-left: 2px solid #333333;
        }
        .diff-neutral {
            color: #888888;
        }

        /* Line numbers */
        .line-num {
            user-select: none;
            color: #444444;
            text-align: right;
            padding-right: 1rem;
            min-width: 3rem;
            display: inline-block;
        }

        /* Smooth Selection */
        ::selection {
            background: #2C67C5;
            color: #FFFFFF;
        }
    </style>
</head>
<body class="font-sans h-screen flex flex-col overflow-hidden select-none p-3 gap-3">

    <!-- FLOATING TOP NAVBAR ISLAND -->
    <header class="h-14 liquid-glass rounded-2xl flex items-center justify-between px-5 z-20 shrink-0 border border-white/10">
        
        <!-- Left Section: Clean Repository Name -->
        <div class="flex items-center space-x-3">
            <span class="tracking-tight text-white font-bold text-base">Mini<span class="text-[#2C67C5]">Git</span></span>
            <span class="text-white/20 text-sm">/</span>
            <span id="repoNamePill" class="liquid-pill text-white font-mono text-xs px-3 py-1 rounded-full font-medium border border-[#2C67C5]/30 bg-[#2C67C5]/10">repo</span>
        </div>

        <!-- Center Section: Segmented View Switcher -->
        <div class="segmented-track rounded-full p-1 flex items-center shadow-lg">
            <button id="tabBtnWorkspace" onclick="switchMainView('workspace')" class="px-4 py-1 rounded-full text-xs font-semibold bg-[#2C67C5] text-white flex items-center space-x-1.5 transition-all cursor-pointer">
                <i class="fa-solid fa-folder-tree text-xs"></i>
                <span>Workspace</span>
            </button>
            <button id="tabBtnChanges" onclick="switchMainView('changes')" class="px-4 py-1 rounded-full text-xs font-medium text-white/70 hover:text-white hover:bg-white/10 flex items-center space-x-1.5 transition-all cursor-pointer relative">
                <i class="fa-solid fa-code-compare text-xs"></i>
                <span>Changes &amp; Diff</span>
                <span id="changesCountBadge" class="hidden ml-1 px-1.5 py-0.2 bg-[#2C67C5] text-white text-[10px] font-bold rounded-full">0</span>
            </button>
            <button id="tabBtnGraph" onclick="switchMainView('graph')" class="px-4 py-1 rounded-full text-xs font-medium text-white/70 hover:text-white hover:bg-white/10 flex items-center space-x-1.5 transition-all cursor-pointer">
                <i class="fa-solid fa-diagram-project text-xs"></i>
                <span>Commit Graph</span>
            </button>
            <button id="tabBtnLog" onclick="switchMainView('log')" class="px-4 py-1 rounded-full text-xs font-medium text-white/70 hover:text-white hover:bg-white/10 flex items-center space-x-1.5 transition-all cursor-pointer">
                <i class="fa-solid fa-clock-rotate-left text-xs"></i>
                <span>Commits Log</span>
            </button>
        </div>

        <!-- Right Section: Branch Info & CLI Helper -->
        <div class="flex items-center space-x-2.5">
            <!-- Active Branch Pill -->
            <div id="branchIndicator" class="flex items-center liquid-pill rounded-full px-3.5 py-1.5 text-xs font-mono font-medium border border-[#2C67C5]/30 bg-[#2C67C5]/10">
                <span class="w-1.5 h-1.5 rounded-full bg-[#2C67C5] mr-2"></span>
                <i class="fa-solid fa-code-branch text-[#2C67C5] mr-2 text-[11px]"></i>
                <span class="text-white/50 mr-1.5 font-sans">Branch:</span>
                <span id="currentBranchDisplay" class="text-white font-semibold">main</span>
            </div>

            <!-- CLI Helper Button -->
            <button onclick="toggleCliDrawer()" class="liquid-pill text-xs text-white px-3.5 py-1.5 rounded-full flex items-center space-x-1.5 font-medium hover:border-[#2C67C5]/40 hover:bg-[#2C67C5]/10 transition-all">
                <i class="fa-solid fa-terminal text-[#2C67C5] text-[11px]"></i>
                <span>CLI Helper</span>
            </button>
        </div>
    </header>

    <!-- MAIN CONTENT AREA -->
    <div class="flex flex-1 gap-3 overflow-hidden min-h-0">

        <!-- ================================================================= -->
        <!-- VIEW 1: WORKSPACE & CODE VIEWER -->
        <!-- ================================================================= -->
        <div id="viewWorkspace" class="flex flex-1 gap-3 overflow-hidden">
            
            <!-- Left Sidebar: File Explorer Tree -->
            <aside class="w-80 liquid-glass rounded-2xl flex flex-col shrink-0 overflow-hidden">
                <div class="p-3.5 border-b border-white/10 flex items-center justify-between">
                    <span class="text-xs font-semibold uppercase tracking-wider text-white/60">Repository Files</span>
                    <span id="workspaceFileCount" class="text-[11px] bg-white/10 px-2.5 py-0.5 rounded-full text-white font-mono font-medium">0 files</span>
                </div>
                <!-- File Tree Container -->
                <div id="fileTreeContainer" class="flex-1 overflow-y-auto p-3 space-y-1 font-mono text-sm">
                    <!-- Populated dynamically -->
                </div>
                <!-- Bottom Stats -->
                <div class="p-3 border-t border-white/10 bg-black/40 text-xs text-white/50 flex justify-between items-center">
                    <span id="totalCommitsCount">0 commits</span>
                    <span id="totalBranchesCount">0 branches</span>
                </div>
            </aside>

            <!-- Right Main Panel: Clean Read-Only Code Viewer -->
            <main class="flex-1 liquid-glass rounded-2xl flex flex-col overflow-hidden relative">
                <!-- Code Header & File Details -->
                <div class="h-12 bg-black/50 border-b border-white/10 flex items-center justify-between px-4 text-xs shrink-0">
                    <div class="flex items-center space-x-2 truncate">
                        <i id="codeHeaderIcon" class="fa-regular fa-file-code text-[#2C67C5] text-sm"></i>
                        <span id="codeFilePath" class="text-white font-mono font-semibold text-sm truncate">Select a file</span>
                        <span id="codeLineCount" class="text-white/40 text-xs ml-2 font-mono"></span>
                    </div>
                    <div class="flex items-center space-x-2">
                        <!-- Commit Details Pill for this file -->
                        <div id="fileCommitPill" class="hidden items-center space-x-1.5 liquid-pill px-3 py-1 rounded-full text-[11px] font-mono cursor-pointer border border-[#2C67C5]/30 bg-[#2C67C5]/10 hover:bg-[#2C67C5]/20" onclick="showActiveFileCommitHistory()">
                            <i class="fa-solid fa-code-commit text-[#2C67C5]"></i>
                            <span id="fileCommitHash" class="text-[#2C67C5] font-semibold"></span>
                            <span id="fileCommitMsg" class="text-white/60 max-w-[150px] truncate hidden md:inline"></span>
                        </div>
                        <button onclick="copyCodeToClipboard()" class="liquid-pill text-xs px-3.5 py-1 rounded-full text-white font-medium flex items-center space-x-1.5 hover:border-[#2C67C5]/40 hover:text-[#2C67C5]" title="Copy file content">
                            <i class="fa-regular fa-copy text-xs"></i>
                            <span id="copyBtnText">Copy</span>
                        </button>
                    </div>
                </div>

                <!-- Code Content Container with Line Numbers -->
                <div class="flex-1 overflow-y-auto overflow-x-auto p-4 font-mono text-xs leading-relaxed flex select-text bg-black/30" id="codeContainer">
                    <div id="codeLineNumbers" class="line-num select-none"></div>
                    <pre id="codeContent" class="flex-1 text-white whitespace-pre overflow-x-visible font-mono"></pre>
                </div>
            </main>

        </div>

        <!-- ================================================================= -->
        <!-- VIEW 2: CHANGES & SIDE-BY-SIDE DIFF -->
        <!-- ================================================================= -->
        <div id="viewChanges" class="hidden flex-1 gap-3 overflow-hidden">
            
            <!-- Left Sidebar: Changed Files List -->
            <aside class="w-80 liquid-glass rounded-2xl flex flex-col shrink-0 overflow-hidden">
                <div class="p-3.5 border-b border-white/10 flex items-center justify-between">
                    <span class="text-xs font-semibold uppercase tracking-wider text-white/60">Source Control</span>
                    <span id="totalChangesPill" class="text-[11px] bg-[#2C67C5] text-white font-bold px-2.5 py-0.5 rounded-full">0 changes</span>
                </div>

                <div class="flex-1 overflow-y-auto p-3 space-y-4">
                    <!-- Staged Changes Section -->
                    <div>
                        <div class="text-[11px] font-semibold text-white/60 uppercase tracking-wider mb-2 flex items-center justify-between">
                            <span>Staged Changes</span>
                            <span id="stagedCountDisplay" class="font-mono text-[#2C67C5] font-bold">(0)</span>
                        </div>
                        <div id="stagedListContainer" class="space-y-1 font-mono text-xs">
                            <!-- Populated dynamically -->
                        </div>
                    </div>

                    <!-- Unstaged Working Directory Changes -->
                    <div>
                        <div class="text-[11px] font-semibold text-white/60 uppercase tracking-wider mb-2 flex items-center justify-between">
                            <span>Working Directory Changes</span>
                            <span id="unstagedCountDisplay" class="font-mono text-white font-bold">(0)</span>
                        </div>
                        <div id="unstagedListContainer" class="space-y-1 font-mono text-xs">
                            <!-- Populated dynamically -->
                        </div>
                    </div>
                </div>

                <!-- Quick Terminal Tip -->
                <div class="p-3.5 border-t border-white/10 bg-black/50 text-xs text-white/70 space-y-1">
                    <div class="font-medium text-white flex items-center space-x-1.5">
                        <i class="fa-solid fa-lightbulb text-[#2C67C5]"></i>
                        <span>CLI Quick Hint</span>
                    </div>
                    <p class="text-[11px] text-white/50">Run <code class="text-white font-mono bg-white/10 px-1 py-0.5 rounded">minigit add &lt;file&gt;</code> to stage, and <code class="text-white font-mono bg-white/10 px-1 py-0.5 rounded">minigit commit -m "..."</code> to record changes.</p>
                </div>
            </aside>

            <!-- Right Main Panel: Side-by-Side & Unified Diff Viewer -->
            <main class="flex-1 liquid-glass rounded-2xl flex flex-col overflow-hidden relative">
                <!-- Diff Toolbar -->
                <div class="h-12 bg-black/50 border-b border-white/10 flex items-center justify-between px-4 text-xs shrink-0 font-mono">
                    <div class="flex items-center space-x-2.5">
                        <span class="text-white/50">Diffing:</span>
                        <select id="diffFileSelect" onchange="renderSelectedDiff()" class="liquid-pill text-white px-3 py-1 rounded-lg focus:outline-none cursor-pointer">
                            <!-- Populated dynamically -->
                        </select>
                    </div>
                    <div class="flex items-center space-x-3">
                        <span class="bg-zinc-800 text-zinc-300 border border-zinc-600 px-3 py-0.5 rounded-full flex items-center text-[11px]"><i class="fa-solid fa-minus mr-1.5"></i> HEAD Baseline</span>
                        <span class="bg-[#2C67C5] text-white font-semibold px-3 py-0.5 rounded-full flex items-center text-[11px]"><i class="fa-solid fa-plus mr-1.5"></i> Working Copy</span>
                    </div>
                </div>

                <!-- Diff Content Grid -->
                <div class="flex-1 grid grid-cols-2 divide-x divide-white/10 font-mono text-xs overflow-y-auto">
                    <!-- Left: Baseline (Head) -->
                    <div class="p-4 bg-black/40 overflow-x-auto">
                        <div class="text-white/40 border-b border-white/10 pb-1 mb-2 font-bold uppercase text-[10px] tracking-wider">HEAD Commit Version</div>
                        <div id="diffOriginalLines" class="space-y-0.5"></div>
                    </div>
                    <!-- Right: Working Copy -->
                    <div class="p-4 bg-black/40 overflow-x-auto">
                        <div class="text-white/40 border-b border-white/10 pb-1 mb-2 font-bold uppercase text-[10px] tracking-wider">Working Copy Version</div>
                        <div id="diffModifiedLines" class="space-y-0.5"></div>
                    </div>
                </div>
            </main>

        </div>

        <!-- ================================================================= -->
        <!-- VIEW 3: INTERACTIVE COMMIT GRAPH (DAG) -->
        <!-- ================================================================= -->
        <div id="viewGraph" class="hidden flex-1 liquid-glass rounded-2xl flex flex-col overflow-hidden p-4 relative">
            <div class="flex justify-between items-center mb-3 shrink-0">
                <div class="flex items-center space-x-3">
                    <h3 class="text-sm font-semibold text-white flex items-center space-x-2">
                        <i class="fa-solid fa-diagram-project text-white/80"></i>
                        <span>Directed Acyclic Graph (DAG)</span>
                    </h3>
                    <span class="text-xs text-white/40">Click any commit to inspect details</span>
                </div>
                <div class="flex items-center space-x-3 text-xs text-white/60">
                    <span class="flex items-center space-x-1.5"><span class="w-2.5 h-2.5 rounded-full bg-[#2C67C5] inline-block"></span> <span>HEAD Commit</span></span>
                    <span class="flex items-center space-x-1.5"><span class="w-2.5 h-2.5 rounded-full bg-white inline-block"></span> <span>Commit</span></span>
                    <span class="flex items-center space-x-1.5"><span class="w-2.5 h-0.5 bg-[#2C67C5]/60 inline-block"></span> <span>Parent Edge</span></span>
                </div>
            </div>

            <!-- Interactive Canvas & Inspector Split -->
            <div class="flex-1 flex gap-3 overflow-hidden min-h-0">
                <!-- SVG Canvas Container -->
                <div class="flex-1 bg-black/60 border border-white/10 rounded-2xl relative overflow-y-auto p-4 shadow-inner">
                    <svg id="commitDagSvg" class="w-full h-full min-h-[300px]">
                        <!-- Rendered dynamically -->
                    </svg>
                </div>

                <!-- Commit Inspector Drawer -->
                <div id="commitInspectorDrawer" class="w-80 liquid-glass-subtle rounded-2xl p-4 border border-white/15 flex flex-col space-y-3 overflow-y-auto shrink-0">
                    <span class="text-xs font-semibold uppercase tracking-wider text-white/40">Commit Details</span>
                    <div id="inspectorContent" class="space-y-3 text-xs">
                        <p class="text-white/40 italic">Select a commit from the graph to inspect its tree and metadata.</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- ================================================================= -->
        <!-- VIEW 4: COMMITS LOG & TIMELINE -->
        <!-- ================================================================= -->
        <div id="viewLog" class="hidden flex-1 liquid-glass rounded-2xl flex flex-col overflow-hidden p-5">
            <div class="flex items-center justify-between pb-3 border-b border-white/10 mb-4 shrink-0">
                <div>
                    <h3 class="text-base font-semibold text-white flex items-center space-x-2">
                        <i class="fa-solid fa-clock-rotate-left text-[#2C67C5]"></i>
                        <span>Commit Timeline</span>
                    </h3>
                    <p class="text-xs text-white/40 mt-0.5">Linear chronological log of commits</p>
                </div>
                <span id="logTotalCount" class="liquid-pill text-xs px-3 py-1 rounded-full text-white font-mono border border-[#2C67C5]/30 bg-[#2C67C5]/10">0 commits</span>
            </div>

            <div id="commitTimelineList" class="flex-1 overflow-y-auto space-y-3 pr-2">
                <!-- Populated dynamically -->
            </div>
        </div>

    </div>

    <!-- ================================================================= -->
    <!-- SLIDE-OVER DRAWER: CLI CHEATSHEET & REPO HELPER -->
    <!-- ================================================================= -->
    <div id="cliDrawer" class="fixed inset-0 bg-black/75 z-50 flex justify-end hidden transition-all" onclick="if(event.target === this) toggleCliDrawer()">
        <div class="w-[420px] max-w-[95vw] h-full liquid-glass border-l border-white/20 p-5 flex flex-col space-y-4 shadow-2xl">
            <div class="flex items-center justify-between pb-3 border-b border-white/10 shrink-0">
                <div class="flex items-center space-x-2.5">
                    <div class="w-8 h-8 rounded-full bg-[#2C67C5]/20 border border-[#2C67C5]/40 flex items-center justify-center text-[#2C67C5]">
                        <i class="fa-solid fa-terminal text-sm"></i>
                    </div>
                    <div>
                        <h4 class="text-sm font-semibold text-white">MiniGit CLI Commands</h4>
                        <p class="text-[11px] text-white/50">Run commands in your terminal shell</p>
                    </div>
                </div>
                <button onclick="toggleCliDrawer()" class="w-7 h-7 rounded-full liquid-pill flex items-center justify-center text-white/70 hover:text-white"><i class="fa-solid fa-xmark text-xs"></i></button>
            </div>

            <div class="flex-1 overflow-y-auto space-y-3 pr-1 text-xs">
                <p class="text-white/60 text-xs">Mini-Git operates on your real filesystem via the terminal. After making changes, run <code class="text-white font-mono bg-white/10 px-1 py-0.5 rounded">minigit html</code> to update this view.</p>

                <!-- Command Items -->
                <div class="space-y-2 font-mono">
                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> status</span>
                            <button onclick="copyCommand('minigit status', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">View staged, modified, deleted, and untracked files</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> add .</span>
                            <button onclick="copyCommand('minigit add .', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Stage all working directory changes</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> commit -m "message"</span>
                            <button onclick="copyCommand('minigit commit -m &quot;Updated files&quot;', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Record a snapshot of staged changes</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> diff</span>
                            <button onclick="copyCommand('minigit diff', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Show differences between working files and index</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> branch &lt;name&gt;</span>
                            <button onclick="copyCommand('minigit branch feature', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Create a new branch at current commit</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> checkout &lt;branch&gt;</span>
                            <button onclick="copyCommand('minigit checkout feature', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Switch active branch or visit commit hash</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> merge &lt;branch&gt;</span>
                            <button onclick="copyCommand('minigit merge feature', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Fast-forward merge target branch into current</p>
                    </div>

                    <div class="p-3 bg-white/5 rounded-xl border border-white/10 space-y-1">
                        <div class="flex items-center justify-between text-white font-semibold">
                            <span><span class="text-[#2C67C5]">minigit</span> html</span>
                            <button onclick="copyCommand('minigit html', this)" class="text-[11px] text-[#2C67C5] hover:underline font-sans font-medium">Copy</button>
                        </div>
                        <p class="text-[11px] font-sans text-white/40">Re-generate and refresh this report</p>
                    </div>
                </div>
            </div>

            <div class="pt-2 border-t border-white/10 shrink-0">
                <button onclick="toggleCliDrawer()" class="w-full py-2 bg-[#2C67C5] hover:bg-[#2354a3] text-white font-semibold text-xs rounded-xl transition active:scale-95">Close Helper</button>
            </div>
        </div>
    </div>

    <!-- ================================================================= -->
    <!-- FILE COMMIT HISTORY MODAL -->
    <!-- ================================================================= -->
    <div id="fileHistoryModal" class="fixed inset-0 bg-black/80 z-50 flex items-center justify-center hidden" onclick="if(event.target === this) closeFileHistoryModal()">
        <div class="liquid-glass rounded-3xl p-6 w-[520px] max-w-[95vw] space-y-4 shadow-2xl border border-white/20">
            <div class="flex items-center justify-between border-b border-white/10 pb-3">
                <div class="flex items-center space-x-2.5">
                    <div class="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-white">
                        <i class="fa-solid fa-code-commit text-sm"></i>
                    </div>
                    <div>
                        <h3 class="text-sm font-semibold text-white">File Commit History</h3>
                        <p id="fhmFilePath" class="text-xs text-white/50 font-mono"></p>
                    </div>
                </div>
                <button onclick="closeFileHistoryModal()" class="w-7 h-7 rounded-full liquid-pill flex items-center justify-center text-white/60 hover:text-white"><i class="fa-solid fa-xmark text-xs"></i></button>
            </div>

            <div id="fhmList" class="space-y-2.5 max-h-64 overflow-y-auto pr-1 text-xs">
                <!-- Populated dynamically -->
            </div>

            <div class="flex justify-end pt-2 border-t border-white/10">
                <button onclick="closeFileHistoryModal()" class="px-5 py-2 liquid-pill text-white text-xs rounded-xl font-medium">Close</button>
            </div>
        </div>
    </div>

    <!-- ================================================================= -->
    <!-- CORE SCRIPT & DATA LOGIC -->
    <!-- ================================================================= -->
    <!-- Injected by C++ `minigit html`. Stays `null` when opened standalone. -->
    <script>window.MINIGIT_LIVE = /*__MINIGIT_DATA__*/null;</script>

    <script>
        /* ---------------------------------------------------------------------
         * REPOSITORY STATE
         * --------------------------------------------------------------------- */
        let REPO_DATA = null;
        let ACTIVE_FILE = null;
        let ACTIVE_VIEW = 'workspace';

        // Sample data for standalone preview mode
        const DEMO_REPO = {
            repoName: "minigit-sample",
            generated: new Date().toISOString(),
            currentBranch: "main",
            branches: {
                "main": "c3f81e09a8bc4d1234567890abcdef1234567890",
                "feature": "a1b2c3d4e5f678901234567890abcdef12345678"
            },
            objects: {
                "b111111111111111111111111111111111111111": { type: "blob", content: "<!DOCTYPE html>\n<html>\n<head>\n  <title>Sample MiniGit App</title>\n</head>\n<body>\n  <h1>Welcome to MiniGit</h1>\n  <p>Clean, purposeful version control studio.</p>\n</body>\n</html>" },
                "b222222222222222222222222222222222222222": { type: "blob", content: "// Main Application Entry\nexport function initApp() {\n  console.log('MiniGit engine loaded.');\n  return true;\n}\n" },
                "b333333333333333333333333333333333333333": { type: "blob", content: "body {\n  margin: 0;\n  background: #000;\n  color: #fff;\n  font-family: sans-serif;\n}\n" },
                "b444444444444444444444444444444444444444": { type: "blob", content: "# MiniGit Project\nA C++17 small version control system with high-precision visual studio.\n" },
                "t111111111111111111111111111111111111111": { type: "tree", data: { "index.html": "b111111111111111111111111111111111111111", "src/app.js": "b222222222222222222222222222222222222222", "styles/app.css": "b333333333333333333333333333333333333333", "README.md": "b444444444444444444444444444444444444444" } },
                "c00000000000000000000000000000000000000": { type: "commit", data: { tree: "t111111111111111111111111111111111111111", parent: null, message: "Initial repository commit", author: "Developer <dev@minigit.io>", timestamp: new Date(Date.now() - 86400000).toISOString() } },
                "c3f81e09a8bc4d1234567890abcdef1234567890": { type: "commit", data: { tree: "t111111111111111111111111111111111111111", parent: "c00000000000000000000000000000000000000", message: "Update HTML title and app styling", author: "Developer <dev@minigit.io>", timestamp: new Date().toISOString() } }
            },
            files: {
                "index.html": "<!DOCTYPE html>\n<html>\n<head>\n  <title>Sample MiniGit App</title>\n</head>\n<body>\n  <h1>Welcome to MiniGit</h1>\n  <p>Clean, purposeful version control studio.</p>\n  <p>Added local modifications here.</p>\n</body>\n</html>",
                "src/app.js": "// Main Application Entry\nexport function initApp() {\n  console.log('MiniGit engine loaded.');\n  return true;\n}\n",
                "styles/app.css": "body {\n  margin: 0;\n  background: #000;\n  color: #fff;\n  font-family: sans-serif;\n}\n",
                "README.md": "# MiniGit Project\nA C++17 small version control system with high-precision visual studio.\n"
            },
            staged: {},
            stagedDeleted: []
        };

        /* ---------------------------------------------------------------------
         * INITIALIZATION & BOOTSTRAP
         * --------------------------------------------------------------------- */
        function initApp() {
            REPO_DATA = (window.MINIGIT_LIVE && typeof window.MINIGIT_LIVE === 'object') ? window.MINIGIT_LIVE : DEMO_REPO;

            // Header metadata
            document.getElementById('repoNamePill').textContent = REPO_DATA.repoName || 'repository';
            document.getElementById('currentBranchDisplay').textContent = REPO_DATA.currentBranch || 'main';

            // Workspace and stats
            const files = Object.keys(REPO_DATA.files || {}).sort();
            document.getElementById('workspaceFileCount').textContent = `${files.length} file${files.length === 1 ? '' : 's'}`;
            
            const nCommits = Object.values(REPO_DATA.objects || {}).filter(o => o.type === 'commit').length;
            const nBranches = Object.keys(REPO_DATA.branches || {}).length;
            document.getElementById('totalCommitsCount').textContent = `${nCommits} commit${nCommits === 1 ? '' : 's'}`;
            document.getElementById('totalBranchesCount').textContent = `${nBranches} branch${nBranches === 1 ? '' : 'es'}`;
            document.getElementById('logTotalCount').textContent = `${nCommits} commit${nCommits === 1 ? '' : 's'}`;

            // Render view components
            renderFileTree();
            renderSourceControlLists();
            renderCommitDagGraph();
            renderCommitsLog();

            // Select initial file
            if (files.length > 0) {
                selectFile(files[0]);
            }
        }

        /* ---------------------------------------------------------------------
         * VIEW SWITCHING
         * --------------------------------------------------------------------- */
        function switchMainView(viewName) {
            ACTIVE_VIEW = viewName;
            const views = {
                workspace: document.getElementById('viewWorkspace'),
                changes: document.getElementById('viewChanges'),
                graph: document.getElementById('viewGraph'),
                log: document.getElementById('viewLog'),
            };

            const buttons = {
                workspace: document.getElementById('tabBtnWorkspace'),
                changes: document.getElementById('tabBtnChanges'),
                graph: document.getElementById('tabBtnGraph'),
                log: document.getElementById('tabBtnLog'),
            };

            for (const key in views) {
                if (key === viewName) {
                    views[key].classList.remove('hidden');
                    views[key].classList.add('flex');
                    buttons[key].className = "px-4 py-1 rounded-full text-xs font-semibold bg-[#2C67C5] text-white flex items-center space-x-1.5 transition-all cursor-pointer relative";
                } else {
                    views[key].classList.add('hidden');
                    views[key].classList.remove('flex');
                    buttons[key].className = "px-4 py-1 rounded-full text-xs font-medium text-white/70 hover:text-white hover:bg-white/10 flex items-center space-x-1.5 transition-all cursor-pointer relative";
                }
            }

            if (viewName === 'changes') renderSelectedDiff();
            if (viewName === 'graph') renderCommitDagGraph();
        }

        /* ---------------------------------------------------------------------
         * FILE TREE & CODE VIEWER
         * --------------------------------------------------------------------- */
        function splitPath(filepath) {
            const parts = filepath.split('/');
            if (parts.length > 1) {
                return { folder: parts.slice(0, -1).join('/'), filename: parts[parts.length - 1] };
            }
            return { folder: 'root', filename: filepath };
        }

        function getFileIcon(filename) {
            if (filename.endsWith('.html') || filename.endsWith('.htm')) return '<i class="fa-brands fa-html5 text-[#2C67C5]"></i>';
            if (filename.endsWith('.css')) return '<i class="fa-brands fa-css3-alt text-[#2C67C5]"></i>';
            if (filename.endsWith('.js') || filename.endsWith('.jsx')) return '<i class="fa-brands fa-square-js text-zinc-300"></i>';
            if (filename.endsWith('.json')) return '<i class="fa-solid fa-code text-[#2C67C5]"></i>';
            if (filename.endsWith('.md')) return '<i class="fa-solid fa-file-lines text-zinc-300"></i>';
            return '<i class="fa-regular fa-file-code text-[#2C67C5]"></i>';
        }

        function getFileCommitHistory(filepath) {
            const history = [];
            let currentHash = REPO_DATA.branches[REPO_DATA.currentBranch];

            while (currentHash && REPO_DATA.objects[currentHash]) {
                const commit = REPO_DATA.objects[currentHash].data;
                const treeHash = commit.tree;
                const tree = REPO_DATA.objects[treeHash]?.data || {};
                const blobHash = tree[filepath];

                if (blobHash) {
                    const parentHash = commit.parent;
                    let parentBlob = null;
                    if (parentHash && REPO_DATA.objects[parentHash]) {
                        const parentTreeHash = REPO_DATA.objects[parentHash].data.tree;
                        parentBlob = REPO_DATA.objects[parentTreeHash]?.data?.[filepath];
                    }

                    if (!parentBlob || parentBlob !== blobHash) {
                        history.push({
                            commitHash: currentHash,
                            message: commit.message,
                            author: commit.author,
                            timestamp: commit.timestamp,
                            blobHash
                        });
                    }
                }
                currentHash = commit.parent;
            }
            return history;
        }

        const FOLDER_COLLAPSED = {};

        function renderFileTree() {
            const container = document.getElementById('fileTreeContainer');
            if (!container) return;
            container.innerHTML = '';

            const groups = {};
            for (const filepath of Object.keys(REPO_DATA.files || {})) {
                const { folder } = splitPath(filepath);
                if (!groups[folder]) groups[folder] = [];
                groups[folder].push(filepath);
            }

            const folderKeys = Object.keys(groups).sort((a, b) => {
                if (a === 'root') return -1;
                if (b === 'root') return 1;
                return a.localeCompare(b);
            });

            folderKeys.forEach(folder => {
                const files = groups[folder];
                const isCollapsed = !!FOLDER_COLLAPSED[folder];

                const folderDiv = document.createElement('div');
                folderDiv.className = "mb-2";

                const folderHeader = document.createElement('div');
                folderHeader.className = "flex items-center justify-between px-2.5 py-1.5 bg-white/5 hover:bg-white/10 rounded-xl cursor-pointer text-xs transition-all select-none border border-white/10";
                folderHeader.onclick = () => { FOLDER_COLLAPSED[folder] = !FOLDER_COLLAPSED[folder]; renderFileTree(); };

                const folderName = (folder === 'root' ? '/ (root)' : `${folder}/`);
                folderHeader.innerHTML = `
                    <div class="flex items-center space-x-2 truncate">
                        <i class="fa-solid ${isCollapsed ? 'fa-chevron-right' : 'fa-chevron-down'} text-[10px] text-white/50 w-3 text-center"></i>
                        <i class="fa-solid ${isCollapsed ? 'fa-folder' : 'fa-folder-open'} text-[#2C67C5]"></i>
                        <span class="font-semibold text-white truncate">${esc(folderName)}</span>
                    </div>
                    <span class="text-[10px] bg-white/10 px-2 py-0.5 rounded-full text-white/60 font-mono">${files.length}</span>
                `;
                folderDiv.appendChild(folderHeader);

                if (!isCollapsed) {
                    const filesContainer = document.createElement('div');
                    filesContainer.className = "space-y-1 mt-1 pl-2.5 border-l border-white/15 ml-2";

                    files.forEach(filepath => {
                        const { filename } = splitPath(filepath);
                        const isSelected = (filepath === ACTIVE_FILE);
                        const history = getFileCommitHistory(filepath);
                        const latest = history[0];

                        const fileEl = document.createElement('div');
                        fileEl.className = `p-2 rounded-xl cursor-pointer transition-all ${isSelected ? 'bg-[#2C67C5] text-white font-semibold' : 'hover:bg-white/10 text-zinc-300'}`;
                        fileEl.onclick = () => selectFile(filepath);

                        fileEl.innerHTML = `
                            <div class="flex items-center justify-between">
                                <div class="flex items-center space-x-2 truncate">
                                    ${getFileIcon(filename)}
                                    <span class="truncate text-xs">${esc(filename)}</span>
                                </div>
                                ${latest ? `<span class="text-[10px] ${isSelected ? 'text-white/80 font-mono' : 'text-white/40 font-mono'}">(${latest.commitHash.substring(0, 7)})</span>` : ''}
                            </div>
                        `;
                        filesContainer.appendChild(fileEl);
                    });
                    folderDiv.appendChild(filesContainer);
                }
                container.appendChild(folderDiv);
            });
        }

        function selectFile(filepath) {
            ACTIVE_FILE = filepath;
            const content = REPO_DATA.files[filepath] || "";
            const lines = content.split('\n');

            document.getElementById('codeFilePath').textContent = filepath;
            document.getElementById('codeLineCount').textContent = `${lines.length} lines`;

            const history = getFileCommitHistory(filepath);
            const commitPill = document.getElementById('fileCommitPill');
            if (history.length > 0) {
                commitPill.classList.remove('hidden');
                commitPill.classList.add('flex');
                document.getElementById('fileCommitHash').textContent = history[0].commitHash.substring(0, 7);
                document.getElementById('fileCommitMsg').textContent = history[0].message;
            } else {
                commitPill.classList.add('hidden');
                commitPill.classList.remove('flex');
            }

            // Line numbers & code content
            const lineNums = lines.map((_, i) => i + 1).join('\n');
            document.getElementById('codeLineNumbers').textContent = lineNums;
            document.getElementById('codeContent').textContent = content;

            renderFileTree();
        }

        function copyCodeToClipboard() {
            if (!ACTIVE_FILE) return;
            const content = REPO_DATA.files[ACTIVE_FILE] || "";
            navigator.clipboard.writeText(content).then(() => {
                const btn = document.getElementById('copyBtnText');
                btn.textContent = 'Copied!';
                setTimeout(() => btn.textContent = 'Copy', 1500);
            });
        }

        function showActiveFileCommitHistory() {
            if (!ACTIVE_FILE) return;
            const modal = document.getElementById('fileHistoryModal');
            document.getElementById('fhmFilePath').textContent = ACTIVE_FILE;
            const list = document.getElementById('fhmList');
            list.innerHTML = '';

            const history = getFileCommitHistory(ACTIVE_FILE);
            if (history.length === 0) {
                list.innerHTML = '<div class="p-3 text-center text-white/50 italic">No commits recorded for this file.</div>';
            } else {
                history.forEach(item => {
                    const row = document.createElement('div');
                    row.className = "p-3 bg-white/5 border border-white/10 rounded-xl space-y-1";
                    row.innerHTML = `
                        <div class="flex items-center justify-between">
                            <span class="font-mono text-white font-bold">${item.commitHash.substring(0, 7)}</span>
                            <span class="text-[10px] text-white/50">${new Date(item.timestamp).toLocaleString()}</span>
                        </div>
                        <div class="text-white text-xs font-medium">${esc(item.message)}</div>
                        <div class="text-[10px] text-white/50 pt-1 border-t border-white/10 flex justify-between">
                            <span>${esc(item.author)}</span>
                            <span class="font-mono">Blob: ${item.blobHash.substring(0, 8)}</span>
                        </div>
                    `;
                    list.appendChild(row);
                });
            }
            modal.classList.remove('hidden');
        }

        function closeFileHistoryModal() {
            document.getElementById('fileHistoryModal').classList.add('hidden');
        }

        /* ---------------------------------------------------------------------
         * SOURCE CONTROL & DIFF ENGINE
         * --------------------------------------------------------------------- */
        function getHeadCommitTreeBlobs() {
            const headCommitHash = REPO_DATA.branches[REPO_DATA.currentBranch];
            if (headCommitHash && REPO_DATA.objects[headCommitHash]) {
                const treeHash = REPO_DATA.objects[headCommitHash].data.tree;
                return REPO_DATA.objects[treeHash]?.data || {};
            }
            return {};
        }

        function renderSourceControlLists() {
            const stagedList = document.getElementById('stagedListContainer');
            const unstagedList = document.getElementById('unstagedListContainer');
            stagedList.innerHTML = '';
            unstagedList.innerHTML = '';

            const headTree = getHeadCommitTreeBlobs();
            let stagedCount = 0;
            let unstagedCount = 0;

            const diffOptions = [];

            // Staged items
            for (const [filepath, hash] of Object.entries(REPO_DATA.staged || {})) {
                stagedCount++;
                diffOptions.push(filepath);
                const item = document.createElement('div');
                item.className = "flex items-center justify-between p-2 bg-[#2C67C5]/10 border border-[#2C67C5]/30 rounded-xl cursor-pointer hover:bg-[#2C67C5]/20 transition";
                item.onclick = () => { switchMainView('changes'); selectDiffFile(filepath); };
                item.innerHTML = `
                    <div class="flex items-center space-x-2 truncate">
                        <span class="text-xs bg-[#2C67C5] text-white font-bold px-1.5 rounded-full">A</span>
                        <span class="truncate text-white text-xs">${esc(filepath)}</span>
                    </div>
                `;
                stagedList.appendChild(item);
            }

            // Staged deletions
            for (const filepath of (REPO_DATA.stagedDeleted || [])) {
                stagedCount++;
                const item = document.createElement('div');
                item.className = "flex items-center justify-between p-2 bg-white/5 border border-white/10 rounded-xl";
                item.innerHTML = `
                    <div class="flex items-center space-x-2 truncate">
                        <span class="text-xs bg-zinc-800 text-zinc-300 border border-zinc-600 font-bold px-1.5 rounded-full">D</span>
                        <span class="truncate text-zinc-400 text-xs line-through">${esc(filepath)}</span>
                    </div>
                `;
                stagedList.appendChild(item);
            }

            // Unstaged items: files in working copy vs headTree/staged
            for (const [filepath, content] of Object.entries(REPO_DATA.files || {})) {
                const headHash = headTree[filepath];
                const stagedHash = REPO_DATA.staged?.[filepath];
                const baseHash = stagedHash || headHash;

                const baseBlob = baseHash && REPO_DATA.objects[baseHash]?.type === 'blob' ? REPO_DATA.objects[baseHash].content : null;
                const isModified = baseBlob !== null && baseBlob !== content;
                const isUntracked = !baseHash;

                if (isModified || isUntracked) {
                    unstagedCount++;
                    if (!diffOptions.includes(filepath)) diffOptions.push(filepath);
                    const letter = isUntracked ? 'U' : 'M';
                    const badgeClass = isUntracked ? 'border border-dashed border-zinc-400 text-zinc-300' : 'border border-[#2C67C5]/60 text-[#2C67C5] bg-[#2C67C5]/10';

                    const item = document.createElement('div');
                    item.className = "flex items-center justify-between p-2 bg-white/5 border border-white/10 rounded-xl cursor-pointer hover:bg-white/10 transition";
                    item.onclick = () => { switchMainView('changes'); selectDiffFile(filepath); };
                    item.innerHTML = `
                        <div class="flex items-center space-x-2 truncate">
                            <span class="text-xs font-bold px-1.5 py-0.2 rounded-full ${badgeClass}">${letter}</span>
                            <span class="truncate text-white text-xs">${esc(filepath)}</span>
                        </div>
                    `;
                    unstagedList.appendChild(item);
                }
            }

            // Deleted on disk
            for (const filepath of Object.keys(headTree)) {
                if (REPO_DATA.files[filepath] === undefined && !(REPO_DATA.stagedDeleted || []).includes(filepath)) {
                    unstagedCount++;
                    const item = document.createElement('div');
                    item.className = "flex items-center justify-between p-2 bg-white/5 border border-white/10 rounded-xl";
                    item.innerHTML = `
                        <div class="flex items-center space-x-2 truncate">
                            <span class="text-xs font-bold bg-zinc-800 text-zinc-300 border border-zinc-600 px-1.5 rounded-full">D</span>
                            <span class="truncate text-zinc-400 text-xs line-through">${esc(filepath)}</span>
                        </div>
                    `;
                    unstagedList.appendChild(item);
                }
            }

            document.getElementById('stagedCountDisplay').textContent = `(${stagedCount})`;
            document.getElementById('unstagedCountDisplay').textContent = `(${unstagedCount})`;
            document.getElementById('totalChangesPill').textContent = `${stagedCount + unstagedCount} changes`;

            const badge = document.getElementById('changesCountBadge');
            if (stagedCount + unstagedCount > 0) {
                badge.textContent = stagedCount + unstagedCount;
                badge.classList.remove('hidden');
            } else {
                badge.classList.add('hidden');
            }

            // Populate diff file selector
            const select = document.getElementById('diffFileSelect');
            select.innerHTML = '';
            const allFiles = diffOptions.length ? diffOptions : Object.keys(REPO_DATA.files || {});
            allFiles.forEach(f => {
                const opt = document.createElement('option');
                opt.value = f;
                opt.textContent = f;
                opt.className = "bg-black text-white font-mono";
                select.appendChild(opt);
            });
        }

        function selectDiffFile(filepath) {
            const select = document.getElementById('diffFileSelect');
            select.value = filepath;
            renderSelectedDiff();
        }

        function renderSelectedDiff() {
            const select = document.getElementById('diffFileSelect');
            const filepath = select.value || Object.keys(REPO_DATA.files || {})[0];
            if (!filepath) return;

            const headTree = getHeadCommitTreeBlobs();
            const blobHash = headTree[filepath];
            let originalContent = "";
            if (blobHash && REPO_DATA.objects[blobHash]) {
                originalContent = REPO_DATA.objects[blobHash].content || "";
            }

            const modifiedContent = REPO_DATA.files[filepath] || "";

            const toLines = (t) => {
                if (t === "") return [];
                const l = t.split('\n').map(x => x.replace(/\r$/, ''));
                if (l.length && l[l.length - 1] === '') l.pop();
                return l;
            };

            const rows = diffLines(toLines(originalContent), toLines(modifiedContent));

            const origContainer = document.getElementById('diffOriginalLines');
            const modContainer = document.getElementById('diffModifiedLines');
            origContainer.innerHTML = '';
            modContainer.innerHTML = '';

            let io = 0, im = 0;
            for (const r of rows) {
                const elOrig = document.createElement('div');
                const elMod = document.createElement('div');
                if (r.kind === 'keep') {
                    io++; im++;
                    elOrig.className = 'diff-neutral px-2 py-0.5 font-mono';
                    elOrig.innerText = `${io}  ${r.text}`;
                    elMod.className = 'diff-neutral px-2 py-0.5 font-mono';
                    elMod.innerText = `${im}  ${r.text}`;
                } else if (r.kind === 'remove') {
                    io++;
                    elOrig.className = 'diff-removed px-2 py-0.5 font-mono rounded';
                    elOrig.innerText = `${io} - ${r.text}`;
                    elMod.className = 'px-2 py-0.5 font-mono';
                    elMod.innerText = '\u00A0';
                } else {
                    im++;
                    elMod.className = 'diff-added px-2 py-0.5 font-mono rounded';
                    elMod.innerText = `${im} + ${r.text}`;
                    elOrig.className = 'px-2 py-0.5 font-mono';
                    elOrig.innerText = '\u00A0';
                }
                origContainer.appendChild(elOrig);
                modContainer.appendChild(elMod);
            }
        }

        function diffLines(a, b) {
            const n = a.length, m = b.length;
            const dp = Array.from({ length: n + 1 }, () => new Uint32Array(m + 1));
            for (let i = n - 1; i >= 0; i--)
                for (let j = m - 1; j >= 0; j--)
                    dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
            const rows = [];
            let i = 0, j = 0;
            while (i < n && j < m) {
                if (a[i] === b[j]) { rows.push({ kind: 'keep', text: a[i] }); i++; j++; }
                else if (dp[i + 1][j] >= dp[i][j + 1]) rows.push({ kind: 'remove', text: a[i++] });
                else rows.push({ kind: 'add', text: b[j++] });
            }
            while (i < n) rows.push({ kind: 'remove', text: a[i++] });
            while (j < m) rows.push({ kind: 'add', text: b[j++] });
            return rows;
        }

        /* ---------------------------------------------------------------------
         * COMMIT DAG GRAPH RENDERER
         * --------------------------------------------------------------------- */
        function renderCommitDagGraph() {
            const svg = document.getElementById('commitDagSvg');
            if (!svg) return;
            svg.innerHTML = '';
            const NS = 'http://www.w3.org/2000/svg';
            const mk = (tag, attrs, text) => {
                const e = document.createElementNS(NS, tag);
                for (const k in attrs) e.setAttribute(k, attrs[k]);
                if (text !== undefined) e.textContent = text;
                svg.appendChild(e);
                return e;
            };

            const commits = {};
            for (const [hash, obj] of Object.entries(REPO_DATA.objects || {})) {
                if (obj.type === 'commit') commits[hash] = { hash, ...obj.data };
            }

            const depthMemo = {};
            const depthOf = (h) => {
                const stack = [];
                let cur = h;
                while (cur && commits[cur] && depthMemo[cur] === undefined) { stack.push(cur); cur = commits[cur].parent; }
                let d = (cur && commits[cur]) ? depthMemo[cur] : -1;
                while (stack.length) depthMemo[stack.pop()] = ++d;
                return depthMemo[h];
            };

            const nodes = Object.values(commits).sort((a, b) =>
                (new Date(a.timestamp) - new Date(b.timestamp)) || (depthOf(a.hash) - depthOf(b.hash)));

            const order = [REPO_DATA.currentBranch, ...Object.keys(REPO_DATA.branches || {}).filter(b => b !== REPO_DATA.currentBranch)];
            const lane = {};
            order.forEach((b, idx) => {
                let cur = REPO_DATA.branches[b];
                while (cur && commits[cur] && lane[cur] === undefined) { lane[cur] = idx; cur = commits[cur].parent; }
            });
            const usedLanes = [...new Set(nodes.map(n => lane[n.hash] ?? 0))].sort((a, b) => a - b);
            const laneX = (l) => 40 + usedLanes.indexOf(l) * 32;
            const nodeX = (n) => laneX(lane[n.hash] ?? 0);
            const textX = 40 + Math.max(0, usedLanes.length - 1) * 32 + 28;

            const rowH = 60, top = 40;
            const yOf = {};
            nodes.forEach((n, i) => { yOf[n.hash] = top + i * rowH; });
            svg.style.height = Math.max(300, top * 2 + nodes.length * rowH) + 'px';

            // Connector lines
            nodes.forEach(n => {
                if (n.parent && commits[n.parent]) {
                    mk('line', { x1: nodeX(commits[n.parent]), y1: yOf[n.parent], x2: nodeX(n), y2: yOf[n.hash], stroke: '#2C67C5', 'stroke-width': 2.5, 'stroke-linecap': 'round', 'stroke-opacity': '0.7' });
                }
            });

            // Commit Nodes
            nodes.forEach(n => {
                const x = nodeX(n), y = yOf[n.hash];
                const isHead = (n.hash === REPO_DATA.branches[REPO_DATA.currentBranch]);

                const circle = mk('circle', {
                    cx: x, cy: y, r: isHead ? 11 : 9,
                    fill: isHead ? '#2C67C5' : '#FFFFFF',
                    stroke: isHead ? '#FFFFFF' : '#2C67C5',
                    'stroke-width': 2.5,
                    class: 'cursor-pointer hover:r-[13] transition-all'
                });
                circle.onclick = () => inspectCommit(n);

                const firstLine = String(n.message || '').split('\n')[0];
                const label = `[${n.hash.substring(0, 7)}] ${firstLine.length > 50 ? firstLine.slice(0, 47) + '...' : firstLine}`;
                const textNode = mk('text', { x: textX, y: y + 4, fill: '#FFFFFF', 'font-size': '12px', 'font-family': 'JetBrains Mono, monospace', 'font-weight': isHead ? '600' : '500', class: 'cursor-pointer hover:fill-[#2C67C5]' }, label);
                textNode.onclick = () => inspectCommit(n);

                // Branch badges
                let lx = textX + label.length * 7.3 + 14;
                for (const [bName, bHash] of Object.entries(REPO_DATA.branches || {})) {
                    if (bHash !== n.hash) continue;
                    const w = bName.length * 7 + 22;
                    const isCur = (bName === REPO_DATA.currentBranch);
                    mk('rect', { x: lx, y: y - 11, width: w, height: 22, rx: 11, fill: isCur ? '#2C67C5' : '#111111', stroke: '#2C67C5', 'stroke-width': isCur ? 1.5 : 1, 'stroke-opacity': isCur ? '1' : '0.6' });
                    mk('text', { x: lx + w / 2, y: y + 4, fill: '#FFFFFF', 'font-size': '10px', 'text-anchor': 'middle', 'font-weight': 'bold', 'font-family': 'Inter, sans-serif' }, bName);
                    lx += w + 8;
                }
            });

            if (nodes.length > 0) inspectCommit(nodes[nodes.length - 1]);
        }

        function inspectCommit(commit) {
            const container = document.getElementById('inspectorContent');
            if (!container) return;

            const treeObj = REPO_DATA.objects[commit.tree];
            const treeEntries = treeObj?.type === 'tree' ? Object.keys(treeObj.data) : [];

            container.innerHTML = `
                <div class="p-3 bg-[#2C67C5]/10 rounded-xl border border-[#2C67C5]/30 space-y-1.5 font-mono">
                    <div class="text-[#2C67C5] font-bold text-xs truncate">[${commit.hash.substring(0, 7)}]</div>
                    <div class="text-[10px] text-white/50 truncate">Full: ${commit.hash}</div>
                </div>

                <div class="space-y-1">
                    <span class="text-[10px] uppercase font-semibold text-white/40 tracking-wider">Message</span>
                    <div class="text-white font-medium text-xs bg-white/5 p-2.5 rounded-xl border border-white/10">${esc(commit.message)}</div>
                </div>

                <div class="space-y-1 text-xs">
                    <div class="flex justify-between py-1 border-b border-white/10">
                        <span class="text-white/40">Author:</span>
                        <span class="text-white truncate max-w-[170px]">${esc(commit.author)}</span>
                    </div>
                    <div class="flex justify-between py-1 border-b border-white/10">
                        <span class="text-white/40">Parent:</span>
                        <span class="font-mono text-[#2C67C5]">${commit.parent ? commit.parent.substring(0, 7) : '(root commit)'}</span>
                    </div>
                    <div class="flex justify-between py-1 border-b border-white/10">
                        <span class="text-white/40">Tree:</span>
                        <span class="font-mono text-[#2C67C5]">${commit.tree.substring(0, 7)}</span>
                    </div>
                </div>

                <div class="space-y-1.5 pt-1">
                    <span class="text-[10px] uppercase font-semibold text-white/40 tracking-wider">Snapshot Files (${treeEntries.length})</span>
                    <div class="space-y-1 max-h-40 overflow-y-auto pr-1 font-mono text-[11px]">
                        ${treeEntries.map(f => `<div class="p-1.5 bg-black rounded border border-white/10 hover:border-[#2C67C5]/40 truncate flex items-center space-x-1.5"><i class="fa-regular fa-file-lines text-[#2C67C5] text-[10px]"></i><span>${esc(f)}</span></div>`).join('')}
                    </div>
                </div>
            `;
        }

        /* ---------------------------------------------------------------------
         * COMMITS LOG TIMELINE
         * --------------------------------------------------------------------- */
        function renderCommitsLog() {
            const list = document.getElementById('commitTimelineList');
            if (!list) return;
            list.innerHTML = '';

            const commits = [];
            for (const [hash, obj] of Object.entries(REPO_DATA.objects || {})) {
                if (obj.type === 'commit') commits.push({ hash, ...obj.data });
            }

            commits.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

            commits.forEach(c => {
                const item = document.createElement('div');
                item.className = "p-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl transition space-y-2";

                const branchLabels = [];
                for (const [bName, bHash] of Object.entries(REPO_DATA.branches || {})) {
                    if (bHash === c.hash) {
                        const isCur = (bName === REPO_DATA.currentBranch);
                        branchLabels.push(`<span class="px-2 py-0.5 rounded-full text-[10px] font-bold ${isCur ? 'bg-[#2C67C5] text-white' : 'bg-black text-white border border-[#2C67C5]/40'}">${esc(bName)}</span>`);
                    }
                }

                item.innerHTML = `
                    <div class="flex items-center justify-between">
                        <div class="flex items-center space-x-2">
                            <span class="font-mono text-[#2C67C5] font-bold text-xs bg-[#2C67C5]/10 px-2 py-0.5 rounded-md border border-[#2C67C5]/30">${c.hash.substring(0, 7)}</span>
                            ${branchLabels.join(' ')}
                        </div>
                    </div>
                    <div class="text-white text-sm font-semibold">${esc(c.message)}</div>
                    <div class="flex items-center justify-between text-xs text-white/40 pt-2 border-t border-white/10">
                        <span><i class="fa-regular fa-user mr-1.5 text-[#2C67C5]"></i>${esc(c.author)}</span>
                        <span class="font-mono text-[11px]"><i class="fa-solid fa-tree mr-1 text-[#2C67C5]"></i>Tree: ${c.tree.substring(0, 7)}</span>
                    </div>
                `;
                list.appendChild(item);
            });
        }

        /* ---------------------------------------------------------------------
         * UTILITIES & CLIPBOARD
         * --------------------------------------------------------------------- */
        function toggleCliDrawer() {
            document.getElementById('cliDrawer').classList.toggle('hidden');
        }

        function copyCommand(cmd, btn) {
            navigator.clipboard.writeText(cmd).then(() => {
                const orig = btn.textContent;
                btn.textContent = 'Copied!';
                setTimeout(() => btn.textContent = orig, 1500);
            });
        }

        function esc(s) {
            return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
        }

        window.onload = function() {
            initApp();
        };
    </script>
</body>
</html>
)MGHTML";
