#!/usr/bin/env python3
"""Regenerate include/FrontendTemplate.h from templates/frontend.html.

Only needed after you edit templates/frontend.html:
    python tools/embed_frontend.py
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
html = (root / "templates" / "frontend.html").read_text(encoding="utf-8").replace("\r\n", "\n")
delim = "MGHTML"
assert f"){delim}\"" not in html, "template contains the raw-string terminator"

out = (
    "// AUTO-GENERATED by tools/embed_frontend.py from templates/frontend.html -- do not edit by hand.\n"
    "#pragma once\n\n"
    f"inline const char kFrontendTemplate[] = R\"{delim}({html}){delim}\";\n"
)
(root / "include" / "FrontendTemplate.h").write_text(out, encoding="utf-8", newline="\n")
print(f"wrote include/FrontendTemplate.h ({len(html)} bytes of HTML)")
